# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a858cbea03684443331c44a92b890304f0dad49a081accd0d521e2fc35d016bf21c2754d44681cfff7109170b26a27d048ddefb737b687b8b6198e5ac73e0d

test:
  secret_key_base: c04f0b4cb8099e3b42fd8e3916ed144b7f60c4b1454c5aa18e416358f3889124847e9b572e5db27291901329034e65bcd3d0d68fb001ae70fcb4cfe4b04b06e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
